apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-config
#data:
  # nothing
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secret
type: Opaque
data:
  POSTGRES_URI: {{ printf "jdbc:postgresql://%s-postgresql:%s/%s" .Chart.Name .Values.postgresql.service.port .Values.postgresql.postgresqlDatabase | b64enc | quote }}
  POSTGRES_USER: {{ .Values.postgresql.postgresqlUsername | b64enc | quote }}
  POSTGRES_PASS: {{ .Values.postgresql.postgresqlPassword | b64enc | quote }}
