apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.app.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
      version: {{ .Chart.AppVersion }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
        version: {{ .Chart.AppVersion }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.app.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: {{ .Values.app.port }}
              protocol: TCP
          env:
            - name: otus.version
              value: "{{ .Chart.AppVersion }}"
            - name: server.port
              value: "{{ .Values.app.port }}"
            - name: spring.datasource.url
              valueFrom:
                secretKeyRef:
                  name: "{{ .Chart.Name }}-secret"
                  key: POSTGRES_URI
            - name: spring.datasource.username
              valueFrom:
                secretKeyRef:
                  name: "{{ .Chart.Name }}-secret"
                  key: POSTGRES_USER
            - name: spring.datasource.password
              valueFrom:
                secretKeyRef:
                  name: "{{ .Chart.Name }}-secret"
                  key: POSTGRES_PASS
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 2
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 5
