apiVersion: skaffold/v2beta2
kind: Config
metadata:
  name: devops
build:
  artifacts:
  - image: palevo/otus
deploy:
  kubectl:
    manifests:
    - kubernetes/deployment.yaml
    - kubernetes/ingress.yaml
    - kubernetes/service.yaml
