apiVersion: skaffold/v2beta2
kind: Config
metadata:
  name: otus
build:
  artifacts:
  - image: palevo/otus
deploy:
  kubectl:
    manifests:
    - kube/deployment.yaml
    - kube/ingress.yaml
    - kube/service.yaml
