prometheus:
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/rewrite-target: /$1
      nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    hosts:
      - arch.homework
    paths:
      - /prometheus/?(.*)
  prometheusSpec:
    externalUrl: http://arch.homework/prometheus/
    serviceMonitorSelectorNilUsesHelmValues: false
    serviceMonitorSelector: {}

grafana:
  sidecar:
    dashboards:
      enabled: true
      searchNamespace: ALL
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/rewrite-target: /$1
      nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    hosts:
      - arch.homework
    path: /grafana/?(.*)
  grafana.ini:
    server:
      root_url: http://arch.homework/grafana/
