apiVersion: v1
kind: ConfigMap
metadata:
  name: otus-config
#data:
  # nothing
---
apiVersion: v1
kind: Secret
metadata:
  name: otus-secret
type: Opaque
data:
  DB_URI: {{ printf "jdbc:postgresql://%s:%s/%s" (include "postgresql.fullname" .) .Values.postgresql.service.port .Values.postgresql.postgresqlDatabase | b64enc | quote }}
  DB_USER: {{ .Values.postgresql.postgresqlUsername | b64enc | quote }}
  DB_PASS: {{ .Values.postgresql.postgresqlPassword | b64enc | quote }}
