# Postgres SQL
postgresql:
  enabled: true
  postgresqlUsername: admin
  postgresqlPassword: admin
  postgresqlDatabase: otus-db
  service:
    port: "5432"
  persistence:
    size: 1Gi

# Application settings
app:
  name: "otus-app"
  port: 8000
  replicaCount: 2
  image:
    repository: palevo/otus

serviceAccount:
  create: true
  name: "otus-service"
  annotations: {}

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  annotations: {
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  }
  hosts:
    - host: arch.homework
      paths: ["/otusapp($|/)(.*)"]
  tls: []

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80
