apiVersion: apps/v1
kind: Deployment
metadata:
  name: otus-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: otus-app
  template:
    metadata:
      labels:
        app: otus-app
    spec:
      containers:
        - name: otus-palevo
          image: palevo/otus:latest
          ports:
            - name: web
              containerPort: 8000
          livenessProbe:
            httpGet:
              port: web
              path: /
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 2
          readinessProbe:
            httpGet:
              port: web
              path: /health
            initialDelaySeconds: 10
            periodSeconds: 5
          volumeMounts:
            - mountPath: /srv/otus-palevo-application/config
              name: app-properties
      volumes:
        - name: app-properties
          configMap:
            name: otus-config
            items:
              - key: application.properties
                path: application.properties
