apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "app.name" . }}-init-db
  labels:
  {{- include "app.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: post-install
spec:
  template:
    metadata:
      labels:
        app: {{ include "app.name" . }}-init-db
    spec:
      restartPolicy: Never
      containers:
        - name: {{ include "app.name" . }}-init-db
          image: postgres:latest
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "app.name" . }}-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ include "app.name" . }}-secret
                  key: POSTGRES_PASS
          command:
            - sh
            - "-c"
            - |
              psql postgresql://$POSTGRES_USER:$POSTGRES_PASS@{{ include "postgresql.uri" . }} <<'EOF'
                TRUNCATE TABLE tbl_user;
                INSERT INTO tbl_user (id, name, email) VALUES (1, 'User Name', 'user@email.com');
              EOF
  backoffLimit: 5
