apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "app.name" . }}-init-db
  labels:
  {{- include "app.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: post-upgrade
spec:
  backoffLimit: 1
  template:
    metadata:
      labels:
        app: {{ include "app.name" . }}-init-db
    spec:
      restartPolicy: Never
      containers:
        - name: {{ include "app.name" . }}-init-db
          image: postgres:latest
          command:
            - sh
            - "-c"
            - |
              {{- include "postgresql.initdb" . | nindent 14 }}
