apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  labels:
  {{- include "app.labels" . | nindent 4 }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  labels:
  {{- include "app.labels" . | nindent 4 }}
type: Opaque
data:
  POSTGRES_URI: {{ include "postgresql.jdbc" . | b64enc | quote }}
  POSTGRES_USER: {{ .Values.postgresql.postgresqlUsername | b64enc | quote }}
  POSTGRES_PASS: {{ .Values.postgresql.postgresqlPassword | b64enc | quote }}
