{{- if .Values.apps.api.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "apps.api.name" . }}
  labels:
    app.kubernetes.io/name: {{ include "apps.api.name" . }}
  {{- include "app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.apps.api.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "apps.api.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "apps.api.name" . }}
    spec:
      containers:
        - name: {{ include "apps.api.name" . }}
          image: "{{ .Values.apps.api.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: {{ .Values.apps.api.port }}
              protocol: TCP
          env:
            - name: otus.url
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-config
                  key: BASE_API_URL
            - name: otus.version
              value: {{ .Chart.AppVersion | quote }}
            - name: server.port
              value: {{ .Values.apps.api.port | quote }}
            - name: springdoc.swagger-ui.path
              value: {{ printf "%s" .Values.apps.api.paths.openapi | quote }}
            - name: springdoc.api-docs.path
              value: {{ printf "%s/api-docs" .Values.apps.api.paths.openapi | quote }}
            - name: springdoc.webjars.path
              value: {{ printf "%s/webjars" .Values.apps.api.paths.openapi | quote }}
            - name: spring.application.name
              value: {{ include "apps.api.name" . | quote }}
            - name: spring.datasource.url
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secret
                  key: POSTGRES_URI
            - name: spring.datasource.username
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secret
                  key: POSTGRES_USER
            - name: spring.datasource.password
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secret
                  key: POSTGRES_PASS
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 2
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 5
  {{- end -}}
