{{- if and (eq .Values.apps.auth.enabled true) (eq .Values.apps.auth.metrics.enabled true) -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "apps.auth.name" . }}
  labels:
  {{- include "app.labels" . | nindent 4 }}
spec:
  jobLabel: {{ include "apps.auth.name" . }}
  namespaceSelector:
    matchNames:
      - "{{ $.Release.Namespace }}"
  selector:
    matchLabels:
  {{- include "app.labels" . | nindent 6 }}
  endpoints:
    - interval: 5s
      port: auth-http
      path: /actuator/prometheus
  {{- end -}}
