apiVersion: v1
kind: Service
metadata:
  name: {{ include "apps.api.name" . }}-service
  labels:
    app.kubernetes.io/name: {{ include "apps.api.name" . }}
  {{- include "app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.apps.api.service.type }}
  ports:
    - port: {{ .Values.apps.api.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ include "apps.api.name" . }}
